/*密码验证*/
export const REQUEST_CONFIRM = 'REQUEST_CONFIRM'
export const RECEIVE_CONFIRM = 'RECEIVE_CONFIRM'
export const SELECT_PASSWORD = 'SELECT_PASSWORD'

/*多月查询*/
export const INCREASE = 'INCREASE'
export const SELECT_MONTHS = 'SELECT_MONTHS'
export const INVALIDATE_MONTHS = 'INVALIDATE_MONTHS'
export const REQUEST_GET_MONTHS = 'REQUEST_GET_MONTHS'
export const RECEIVE_GET_MONTHS = 'RECEIVE_GET_MONTHS'
export const STOP_REQUEST = 'STOP_REQUEST'

